repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --line-length=88

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args:
          - --line-length=100

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--ignore=E203,W503"
          - "--per-file-ignores=__init__.py: F401"

  - repo: local
    hooks:
      - id: unit test
        name: unit test
        entry: python3 -m unittest -v tests
        language: system
        types: [python3]



