name: Build & Push Docker Image CI

on:
  push:
    branches:
      - develop
      - test/*
    tags:
      - v*.*.*

  pull_request:
    paths-ignore:
      - ".dev_scripts/**"
      - ".github/**.md"
      - "demo/**"
      - "docker/**"
      - "tools/**"
      - "README.md"

env:
  DOCKERFILE_PATH: "Dockerfile"
  PROJECT_NAME: research
  APP_NAME: clasymm
  PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}

jobs:
  build_cuda_test:
    if: github.event_name == 'pull_request'
    runs-on: ["self-hosted", "linux", "docker", "ubuntu20.04"]
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and install
      run: |
          pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
          pip3 install mmcv-full==1.4.7 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
          pip3 install .[optional]

  build_docker:
    needs: build_cuda_test
    if: ${{ github.ref == 'refs/heads/develop' }} || startsWith(github.event.ref, 'refs/tags')
    runs-on: ["self-hosted", "linux", "docker", "ubuntu20.04"]
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: login container registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
        username: ${{ secrets.CONTAINER_REGISTRY_ID }}
        password: ${{ secrets.CONTAINER_REGISTRY_PW }}

    - name: set tag
      run: |
          echo CONTAINER_TAG=${{github.ref_name}}-$(date +%Y%m%d).${{github.run_number}} | sed -e "s/\//-/g" >> $GITHUB_ENV
    - name: dump version
      run: |
        echo "" >> ${{ env.DOCKERFILE_PATH }}
        echo "ENV GIT_COMMIT_ID=${{ github.sha }} \\" >> ${{ env.DOCKERFILE_PATH }}
        echo "   BUILD_DATE=$(date +%Y.%m.%d) \\" >> ${{ env.DOCKERFILE_PATH }}
        echo "   VERSION=${{ env.CONTAINER_TAG }}" >> ${{ env.DOCKERFILE_PATH }}
        echo "ENV GIT_COMMIT_ID {{ github.sha }}"
        echo "ENV BUILD_DATE $(date +%Y.%m.%d)"
        echo "ENV VERSION ${{ env.CONTAINER_TAG }}"
    - name: build the docker image
      run: |
        docker build . --file ${{ env.DOCKERFILE_PATH }} --tag ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ env.PROJECT_NAME }}/${{ env.APP_NAME }}:${{ env.CONTAINER_TAG }}
    - name: push the docker image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/${{ env.PROJECT_NAME }}/${{ env.APP_NAME }}:${{ env.CONTAINER_TAG }}
