name: deploy

on:
  push:
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-publish:
    runs-on: ["self-hosted", "linux", "ubuntu20.04", "python3"]
    timeout-minutes: 20
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
    - name: checkout main
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: update setuptools
      run: pip3 install setuptools --upgrade
    - name: install dependencies
      run: pip3 install torch==1.9.0 wheel
    - name: Build recls
      run: python3 setup.py sdist bdist_wheel
    - name: publish distribution to PyPI
      run: |
        python3 -m venv myenv
        source myenv/bin/activate
        pip install twine importlib_metadata
        twine upload --repository-url ${{ secrets.PYPI_INDEX_URL }} dist/* -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PW }}

  check-consistency:
    needs: build-n-publish
    runs-on: ["self-hosted", "linux", "ubuntu20.04"]
    steps:
    - name: trigger-dagrun
      run: |
        version=`echo ${{ github.ref_name }} | tr -d "v"`; \
        curl -X POST ${{ secrets.AIRFLOW_RECLS_UPDATE_DAG_URL }} \
        --user "${{ secrets.AIRFLOW_USERNAME }}:${{ secrets.AIRFLOW_PASSWORD }}" \
        -H 'Content-Type: application/json' \
        -d '{"conf": { "version": "'$version'" }}'
